# Base URL
baseurl:

# Site live URL
url: https://fmount.me

# Localhost 
#url: http://127.0.0.1:4000

# Harmony theme configuration. Please change accordingly.
harmony:
  name: "://fmount"
  comments: true
  # Little description about your site
  meta_description:
    Linux
    Virtualization
    fmount
    Networking
    Software Development
    Algorithms
  # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and 
  # in your feed.xml site description.
  #meta_description: > # 
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: fmount
    email: francesco.pantano@linux.com
    url: https://fmount.me

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-66941260-1

  # Profile links, leave blank to ignore
  social: 
    github: fmount
    twitter: fmount9
    keybase: fmount
    rss: feed.xml
# Conversion / Build settings 
  show_disclaimer: true

markdown:    kramdown
#markdown: redcarpet

# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: rouge 

# Permalinks
permalink: pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed

# Add support for the feed RSS
gems:
  - jekyll-feed
feed:
  path: feed.xml

## Add support for AsciiDoc posts using Asciidoctor
#gems:
#  - jekyll-asciidoc
#
#asciidoctor:
#    attributes:
#        - icons=font
#        - hardbreaks!
#        - source-highlighter=coderay

