# Base URL
baseurl:

# Site live URL
url: http://frances-co.github.io

# Localhost 
#url: http://127.0.0.1:4000

# Harmony theme configuration. Please change accordingly.
harmony:
  name: '#frances-co'
  comments: true
  # Little description about your site
  #description: 
  # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and 
  # in your feed.xml site description.
  #meta_description: > # 
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: frances-co
    email: francesco.pan001@gmail.com
    url: http://frances-co.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-65180701-1

  # Profile links, leave blank to ignore
  social: 
    github: frances-co
    keybase: frances_co

# Conversion / Build settings 

markdown:    kramdown
#markdown: redcarpet

# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: pygments 

# Permalinks
permalink: pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed


# Add support for AsciiDoc posts using Asciidoctor
gems:
  - jekyll-asciidoc

asciidoctor:
    attributes:
        - icons=font
        - hardbreaks!
        - source-highlighter=coderay

